title: Cesar's Ramirez CIT_481 Blog 7_2022

logo: /assets/img/paloalto_cortex.png
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
